# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DSS
                                 A QGIS plugin
 Decision Support System
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-27
        copyright            : (C) 2024 by Mushegh Mkrtchyan
        email                : mkrtchyan.mushegh@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DSS class from file DSS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    # from .dss import DSS
    # return DSS(iface)
    
    from .dss_menu import DSSMenuPlugin
    return DSSMenuPlugin(iface)